version: '3.7'

services:
  k3s:
    build: .
    container_name: 'k3s'
    hostname: 'k3s'
    privilieged: true
    ports:
      - 8443:8443
#    environment:
#      - KUBECONFIG: ./k3sconfig
#      - K3S_API_PORT: 8443
