version: "3.7"

services:
  pre-k3s:
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
          echo "alfa"
          echo "bravo"
          echo "charlie"
  k3s:
    build: .
    depends_on:
      - "pre-k3s"
    container_name: "k3s"
    privileged: true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
